import type { Employee } from "@/types/employee"

export const dummyEmployees: Employee[] = [
  {
    dbId: 1,
    id: "EMP001",
    fullName: "Rajesh Kumar",
    mobile: "+91 98765 43210",
    email: "rajesh.kumar@safetymatters.com",
    department: "Fire Safety",
    registrationType: "employee",
    profileStatus: "Verified",
    appStatus: true,
  },
  {
    dbId: 2,
    id: "EMP002",
    fullName: "Priya Sharma",
    mobile: "+91 98765 43211",
    email: "priya.sharma@safetymatters.com",
    department: "Operations",
    registrationType: "employee",
    profileStatus: "Verified",
    appStatus: false,
  },
  {
    dbId: 3,
    id: "EMP003",
    fullName: "Amit Verma",
    mobile: "+91 98765 43212",
    email: "amit.verma@safetymatters.com",
    department: "Technical Services",
    registrationType: "employee",
    profileStatus: "Verified",
    appStatus: true,
  },
  {
    dbId: 4,
    id: "EMP004",
    fullName: "Sneha Reddy",
    mobile: "+91 98765 43213",
    email: "sneha.reddy@safetymatters.com",
    department: "Audit & Compliance",
    registrationType: "employee",
    profileStatus: "Verified",
    appStatus: false,
  },
  {
    dbId: 5,
    id: "EMP005",
    fullName: "Vikram Singh",
    mobile: "+91 98765 43214",
    email: "vikram.singh@safetymatters.com",
    department: "Administration",
    registrationType: "employee",
    profileStatus: "Verified",
    appStatus: true,
  },
  {
    dbId: 6,
    id: "EMP006",
    fullName: "Anjali Nair",
    mobile: "+91 98765 43215",
    email: "anjali.nair@safetymatters.com",
    department: "Fire Safety",
    registrationType: "employee",
    profileStatus: "Verified",
    appStatus: true,
  },
]
